In [350]:
#importando as bibliotecas necessárias

#teste para branch 

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

Importando as bases de dados

In [351]:
df_order_itens = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day 7/DNC_order_items_dataset.csv').drop(['Unnamed: 0'], axis=1)
df_order_reviews = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day 7/DNC_order_reviews_dataset.csv').drop(['Unnamed: 0'], axis=1)
df_order = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day 7/DNC_orders_dataset.csv').drop(['Unnamed: 0'], axis=1)
df_products = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Day 7/DNC_products_dataset.csv').drop(['Unnamed: 0'], axis=1)

In [352]:
df_order_itens.head()

order_id  ...   price
0  00010242fe8c5a6d1ba2dd792cb16214  ...  58.900
1  00018f77f2f0320c557190d7a144bdd3  ... 239.900
2  000229ec398224ef6ca0657da4fc703e  ... 199.000
3  00024acbcdf0a6daa1e931b038114c75  ...  12.990
4  00042b26cf59d7ce69dfabb4e55b4fd9  ... 199.900

[5 rows x 4 columns]

In [353]:
df_order_reviews.head()

review_id  ... review_score
0  7bc2406110b926393aa56f80a40eba40  ...            4
1  80e641a11e56f04c1ad469d5645fdfde  ...            5
2  228ce5500dc1d8e020d8d1322874b6f0  ...            5
3  e64fb393e7b32834bb789ff8bb30750e  ...            5
4  f7c4243c7fe1938f181bec41a392bdeb  ...            5

[5 rows x 3 columns]

In [354]:
df_order.head()

order_id  ... order_status
0  e481f51cbdc54678b7cc49136f2d6af7  ...    delivered
1  53cdb2fc8bc7dce0b6741e2150273451  ...    delivered
2  47770eb9100c2d0c44946d9cf07ec65d  ...    delivered
3  949d5b44dbf5de918fe9c16f97b45f8a  ...    delivered
4  ad21c59c0840e6cb83a9ceb5573f8159  ...    delivered

[5 rows x 3 columns]

In [355]:
df_products.head()

product_id  ... product_width_cm
0  1e9e8ef04dbcff4541ed26657ea517e5  ...           14.000
1  3aa071139cb16b67ca9e5dea641aaa2f  ...           20.000
2  96bd76ec8810374ed1b65e291975717f  ...           15.000
3  cef67bcfe19066a932b7673e239eb23d  ...           26.000
4  9dc1a7de274444849c219cff195d0b71  ...           13.000

[5 rows x 8 columns]

Consolidando todas as bases de dados

In [356]:
df_order_plus_review = df_order_itens.merge(df_order_reviews, on='order_id')


In [357]:
df_order_plus_review_plus_status = df_order_plus_review.merge(df_order, on='order_id')


In [358]:
df_full = df_order_plus_review_plus_status.merge(df_products, on='product_id')
df_full.head()

order_id  ...  product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...            14.000
1  130898c0987d1801452a8ed92a670612  ...            14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...            14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...            14.000
4  7d19f4ef4d04461989632411b7e588b9  ...            14.000

[5 rows x 15 columns]

In [359]:
df_full.shape

(112372, 15)

In [360]:

for columns in df_full:
  porcentagem_de_nulos = (df_full[columns].isnull().sum()/df_full.shape[0])*100
  print(f'a coluna {columns} apresenta {porcentagem_de_nulos}% de nulo')

a coluna order_id apresenta 0.0% de nulo
a coluna order_item_id apresenta 0.0% de nulo
a coluna product_id apresenta 0.0% de nulo
a coluna price apresenta 0.0% de nulo
a coluna review_id apresenta 0.0% de nulo
a coluna review_score apresenta 0.0% de nulo
a coluna customer_id apresenta 0.0% de nulo
a coluna order_status apresenta 0.0% de nulo
a coluna product_category_name apresenta 1.4220624354821485% de nulo
a coluna product_name_lenght apresenta 1.4220624354821485% de nulo
a coluna product_description_lenght apresenta 1.4220624354821485% de nulo
a coluna product_weight_g apresenta 0.016018225180649985% de nulo
a coluna product_length_cm apresenta 0.016018225180649985% de nulo
a coluna product_height_cm apresenta 0.016018225180649985% de nulo
a coluna product_width_cm apresenta 0.016018225180649985% de nulo


In [361]:
df_full.dropna

<bound method DataFrame.dropna of                                 order_id  ...  product_width_cm
0       00010242fe8c5a6d1ba2dd792cb16214  ...            14.000
1       130898c0987d1801452a8ed92a670612  ...            14.000
2       532ed5e14e24ae1f0d735b91524b98b9  ...            14.000
3       6f8c31653edb8c83e1a739408b5ff750  ...            14.000
4       7d19f4ef4d04461989632411b7e588b9  ...            14.000
...                                  ...  ...               ...
112367  ffebd80e3291e811c308365936897efd  ...            22.000
112368  ffee31fb4b5e35c9123608015637c495  ...            20.000
112369  fff7c4452f050315db1b3f24d9df5fcd  ...            15.000
112370  fffa82886406ccf10c7b4e35c4ff2788  ...            15.000
112371  fffe41c64501cc87c801fd61db3f6244  ...            19.000

[112372 rows x 15 columns]>

In [362]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112372 entries, 0 to 112371
Data columns (total 15 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   order_id                    112372 non-null  object 
 1   order_item_id               112372 non-null  int64  
 2   product_id                  112372 non-null  object 
 3   price                       112372 non-null  float64
 4   review_id                   112372 non-null  object 
 5   review_score                112372 non-null  int64  
 6   customer_id                 112372 non-null  object 
 7   order_status                112372 non-null  object 
 8   product_category_name       110774 non-null  object 
 9   product_name_lenght         110774 non-null  float64
 10  product_description_lenght  110774 non-null  float64
 11  product_weight_g            112354 non-null  float64
 12  product_length_cm           112354 non-null  float64
 13  product_height

In [363]:
for columns in df_full:
  x = df_full[columns].nunique()
  print(f'{columns} aprensenta {x} valores distintos')


order_id aprensenta 97917 valores distintos
order_item_id aprensenta 21 valores distintos
product_id aprensenta 32789 valores distintos
price aprensenta 5948 valores distintos
review_id aprensenta 97709 valores distintos
review_score aprensenta 5 valores distintos
customer_id aprensenta 97917 valores distintos
order_status aprensenta 7 valores distintos
product_category_name aprensenta 73 valores distintos
product_name_lenght aprensenta 66 valores distintos
product_description_lenght aprensenta 2958 valores distintos
product_weight_g aprensenta 2200 valores distintos
product_length_cm aprensenta 99 valores distintos
product_height_cm aprensenta 102 valores distintos
product_width_cm aprensenta 95 valores distintos


In [364]:
df_full.order_status.value_counts()

delivered      110013
shipped          1110
canceled          529
invoiced          358
processing        352
unavailable         7
approved            3
Name: order_status, dtype: int64

Verificando a diferença nos status dos pedidos

In [365]:
df_incomplete_order = df_full[df_full['order_status']!='delivered']
df_incomplete_order.head()

order_id  ...  product_width_cm
25   ed2f80d07bcb176e6097b0a730d3d53d  ...            30.000
90   dce5adb99dbd09afb1a7b9a402df9f98  ...            20.000
123  0d760576500ea8611379a97ddcebf3db  ...            40.000
292  6762c128b601a5d3cf6c51958ecec54f  ...            40.000
294  686000ebfaca7883583f123c458a89b7  ...            40.000

[5 rows x 15 columns]

In [366]:
df_incomplete_order.shape

(2359, 15)

In [367]:
df_incomplete_order['order_item_id'].value_counts()

1    2104
2     164
3      41
4      27
5      17
6       6
Name: order_item_id, dtype: int64

In [368]:
df_incomplete_order['review_score'].value_counts()

1    1660
5     213
3     181
2     174
4     131
Name: review_score, dtype: int64

In [369]:
df_complete_order = df_full[df_full['order_status']=='delivered']
df_complete_order.head()

order_id  ...  product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...            14.000
1  130898c0987d1801452a8ed92a670612  ...            14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...            14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...            14.000
4  7d19f4ef4d04461989632411b7e588b9  ...            14.000

[5 rows x 15 columns]

In [370]:
df_complete_order.shape

(110013, 15)

In [371]:
df_full.duplicated().value_counts()

False    112372
dtype: int64

In [372]:
pedidos_entregues = df_complete_order.shape[0]/df_full.shape[0]*100
print(f' a porcentagem de pedidos entregues é de {pedidos_entregues} %') 

 a porcentagem de pedidos entregues é de 97.90072259993593 %


Isto posto, será utilizado apenas os valores dos **pedidos entregues**

In [373]:
df_full = df_full[df_full['order_status']=='delivered']

#Recomendações

#Filtro Colaborativo

## Recomendação dos itens melhores avaliados de acordo com a média (reviews)

In [374]:
df_full.head()

order_id  ...  product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...            14.000
1  130898c0987d1801452a8ed92a670612  ...            14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...            14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...            14.000
4  7d19f4ef4d04461989632411b7e588b9  ...            14.000

[5 rows x 15 columns]

In [375]:
df_full['review_score'].value_counts()

5    63312
4    21184
1    12575
3     9242
2     3700
Name: review_score, dtype: int64

Não temos valores nulos de review

In [376]:
reviews_mean = pd.DataFrame(df_full.groupby(['product_id', 'product_category_name', 'price'])['review_score'].mean())

top10 = reviews_mean.sort_values('review_score', ascending = False).head(10)
top10

review_score
product_id                       product_category_name            price                
00066f42aeeb9f3007548bb9d3f33c38 perfumaria                       101.650         5.000
652c030867f364b558eb9f7dcbcf608d brinquedos                       159.990         5.000
c8e98656b0bfc1efbadc25aa3fb9640e beleza_saude                     107.900         5.000
c8eb5b2d7173db25ec9bfc54dcb4ccbb bebes                            147.990         5.000
653b6b1217fba117599afcc015ffd50a construcao_ferramentas_seguranca 164.900         5.000
6539512c6f2fa68ca44dbfac42dc1f70 automotivo                       194.490         5.000
65330e90e0019aa477e442b9b8e156a1 fashion_roupa_masculina          110.900         5.000
652cee66eaed09b444b43463eee56cc7 fashion_calcados                 220.700         5.000
c8eb5b2d7173db25ec9bfc54dcb4ccbb bebes                            149.550         5.000
652c030867f364b558eb9f7dcbcf608d brinquedos                       179.990         5.000

 ## Recomendação de itens mais populares

In [377]:
count = df_full.groupby(by=['product_id', 'product_category_name'], as_index=False) \
  .agg({'customer_id': pd.Series.nunique}) \
  .rename(columns={'customer_id': 'costumer_count'})

buy_count = count.set_index('product_id')
top10 = buy_count.sort_values('costumer_count', ascending = False).head(10)
top10

product_category_name  costumer_count
product_id                                                              
99a4788cb24856965c36a24e339b6058         cama_mesa_banho             448
aca2eb7d00ea1a7b8ebd4e68314663af        moveis_decoracao             423
422879e10f46682990de24d770e7f83d      ferramentas_jardim             351
d1c427060a0f73f6b889a5c7c61f2ac4  informatica_acessorios             311
389d119b48cf3043d311335e499d9c6b      ferramentas_jardim             308
53b36df67ebb7c41585e8d54d6772e08      relogios_presentes             302
368c6c730842d78016ad823897a372db      ferramentas_jardim             289
53759a2ecddad2bb87a079a1f1519f73      ferramentas_jardim             285
154e7e31ebfa092203795c972e5804a6            beleza_saude             261
2b4609f8948be18874494203496bc318            beleza_saude             254

##Criando o pipeline para a implementação da recomendação

In [378]:
def start_pipeline(dataf):
    return dataf.copy()

def get_item_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
  .agg({'customer_id': pd.Series.nunique}) \
  .rename(columns={'customer_id': 'costumer_count'})\
  .set_index('product_id')\
  .sort_values('costumer_count', ascending = False)

def get_avg_reviews(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

def get_customer_counts(dataf):
  return dataf.groupby(by='customer_id', as_index=False) \
   .agg({'product_id': pd.Series.nunique}) \
   .rename(columns={'product_id': 'product_count'})\
   .set_index('customer_id')\
  #.sort_values('product_count', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(n) \
    .index \
    .tolist()

top_item_reviews = df_full \
  .pipe(start_pipeline) \
  .pipe(get_avg_reviews) \
  .pipe(get_n_top_values, n=10000) #considerando os 10000 produtos melhores avaliados

top_item_sellers = df_full \
  .pipe(start_pipeline) \
  .pipe(get_item_counts) \
  .pipe(get_n_top_values, n=1000)

top_customer_ids= df_full \
  .pipe(start_pipeline) \
  .pipe(get_customer_counts) \
  .pipe(get_n_top_values, n=5000)  

top_item_reviews[:10], top_item_sellers[:10]

(['00066f42aeeb9f3007548bb9d3f33c38',
  '88646c24f1972c70b1da7ab8ff378d8f',
  '8894c64689c2a3a29e2fff744de30e46',
  '888e11f9e6f882701220d1139c58d462',
  '888c70e66e6ead36f2269484a6813212',
  '887ce53cffeba9788502f60e33f1fcf3',
  '8877966d8f081b2857a5e293d6ecf59e',
  '8873909eb9409566f9d5a6d47c4d38c1',
  '88703479ede641552b11881f0d2a6f6b',
  '88596b69f04745db1f8ba135da5c708d'],
 ['99a4788cb24856965c36a24e339b6058',
  'aca2eb7d00ea1a7b8ebd4e68314663af',
  '422879e10f46682990de24d770e7f83d',
  'd1c427060a0f73f6b889a5c7c61f2ac4',
  '389d119b48cf3043d311335e499d9c6b',
  '53b36df67ebb7c41585e8d54d6772e08',
  '368c6c730842d78016ad823897a372db',
  '53759a2ecddad2bb87a079a1f1519f73',
  '154e7e31ebfa092203795c972e5804a6',
  '2b4609f8948be18874494203496bc318'])

In [379]:
matriz_de_relacionamento_top_item_reviews = df_full[df_full["product_id"].isin(top_item_reviews)] \
  .pivot_table(index="product_id", columns= "customer_id", values="review_score").fillna(0)

matriz_de_relacionamento_top_item_reviews.shape

(10000, 12873)

matriz de similaridade

In [380]:
cos_item = cosine_similarity(matriz_de_relacionamento_top_item_reviews)

print(cos_item)
cos_item.shape

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(10000, 10000)

In [381]:
def recomendar(product_id):
  print(f"produto que está interessado: {product_id}")
  try:
    product_idx = matriz_de_relacionamento_top_item_reviews.index.tolist().index(product_id)
    closest_10_products = np.argsort(-cos_item[product_idx])[1:11]
    print(f"Retornando 10 produtos mais próximos de: {product_id}.")
    return matriz_de_relacionamento_top_item_reviews.index[closest_10_products].tolist()
  except ValueError as e:
    print(f"{product_id}, não está incluso na matriz de recomendação. Retornando os 10 mais avaliados")
    return top_item_sellers

In [382]:
id_produto_interesse = "fff9553ac224cec9d15d49f5a263411f"
ids_10_mais_proximos = recomendar(id_produto_interesse)

ids_10_mais_proximos

produto que está interessado: fff9553ac224cec9d15d49f5a263411f
Retornando 10 produtos mais próximos de: fff9553ac224cec9d15d49f5a263411f.


['c42caa5da059e67badc89b89ac1dde34',
 'c432f90fa332fd2e5091f2ac2d226aad',
 'c4332b2ff3cde1b0c62f5b9c8ae84bdc',
 'c438c9c697a57d265dbb6edd8b174b2b',
 'c4444723412f21a52a81a4c14eadc0fa',
 'c445e66ff5aed16191fd41e4d9fcf2aa',
 'c452ed78936fa240d56b35bc146be876',
 'c46b2401e3ccd4e4f779b93093a97e29',
 'c4761af5e6a2183cc23c77a8d16f9d09',
 'c47696608d548c9999a92966e435b3f6']

Os tipos de produto não foram segregados para esse sistema de recomendação

In [383]:
df_full[df_full['product_id']=='fff9553ac224cec9d15d49f5a263411f']

order_id  ...  product_width_cm
109435  df3a7600e4fd0a2c595fa7ad6e2e622e  ...            11.000

[1 rows x 15 columns]

In [384]:
df_full[df_full['product_id']=='c42caa5da059e67badc89b89ac1dde34']

order_id  ...  product_width_cm
108563  d66a9e689fb184277bdd64317e765729  ...            11.000

[1 rows x 15 columns]

# Client based

In [385]:
def transform_sample(dataf):
  return pd.DataFrame({
      "customer": dataf["customer_id"],
      "product": dataf["product_id"],
      "action": dataf["review_score"]
  })

matriz_de_relacionamento_customer_sampled = df_full[df_full['customer_id'].isin(top_customer_ids)] \
  .pipe(transform_sample) \
  .pivot_table(index="customer", columns="product", values="action").fillna(0)

In [386]:
matriz_de_relacionamento_customer_sampled.shape

(5000, 3898)

In [387]:
cos_customer = cosine_similarity(matriz_de_relacionamento_customer_sampled)
print(cos_customer)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [388]:
cos_customer.shape

(5000, 5000)

In [389]:
def recomendar_customer(customer_id):
  print(f"Cliente de interesse: {customer_id}")
  try:
    customer_idx = matriz_de_relacionamento_customer_sampled.index.tolist().index(customer_id)
    closest_10_customers = np.argsort(-cos_customer[customer_idx])[1:11]
    print(f"Retornando 10 clientes mais próximos do cliente: {customer_id}.")
    return matriz_de_relacionamento_customer_sampled.index[closest_10_customers].tolist()
  except ValueError as e:
    print(f"{customer_id}, não está incluso na matriz de recomendação")

In [390]:
id_customer_interesse = '00012a2ce6f8dcda20d059ce98491703'
ids_10_mais_proximos = recomendar_customer(id_customer_interesse)

ids_10_mais_proximos

Cliente de interesse: 00012a2ce6f8dcda20d059ce98491703
Retornando 10 clientes mais próximos do cliente: 00012a2ce6f8dcda20d059ce98491703.


['08fee29b9ac63d1bf53d160c88714bb1',
 '08fe63b02e7e846c85b8a49b9fd540d9',
 '08fd1f647fb132970cc8e3ee6c9075d9',
 '08fc5058d39f827b41d726cac116dfbc',
 '08fc431ce96ad22194b0a00be7100917',
 '08fbfcc1b6c48f73ddca8312c78f6f53',
 '08fb48675dd414001931daa99d6e2ea2',
 '08fabe21a36ebb71c55616524790909b',
 '08faaa96437305ceef6b95a46cfd0030',
 '08fa82297b802757b9b02ced94f8a9e3']

In [391]:
df_full[df_full['customer_id']=='00012a2ce6f8dcda20d059ce98491703']

order_id  ...  product_width_cm
41504  5f79b5b0931d63f1a42989eb65b9da6e  ...            22.000

[1 rows x 15 columns]

In [392]:
df_full[df_full['customer_id']=='08fee29b9ac63d1bf53d160c88714bb1']

order_id  ...  product_width_cm
17775  12767fe9ec8d9dcab0b972043cffb8d3  ...            32.000

[1 rows x 15 columns]